### ISSUE TITLE
Code release?

### ISSUE THREAD

**Issue by maximecb** [sebastianrisi/ga-world-models#1]
I've read your paper on deep neuroevolution and found it very interesting.

A few basic questions:
- When can we expect a code release?
- Do you use a GPU to evaluate neural networks, or is everything CPU-based?
- Could you share more details about the machine you trained on? You say it is a 32-core CPU machine, but is that 32 cores, or 32 threads?
- Did you use any tricks to speed up the evaluation of neural networks / policies?
- Is this implemented in Python + numpy?

**Comment by sebastianrisi** [comment]
Hi, glad you found the paper interesting! The code is now online. It's implemented in Pytorch and we used a machine with 32 virtual CPU cores.

We used one trick to speed up evolution, which we also detail in the paper: evaluations are terminated early if the car drives outside of the track for a certain number of timesteps.

**Comment by sebastianrisi** [comment]
Code released.
